name: 'Check 3rd party licenses'

on:
  pull_request:
  push:
    branches:
      - android-target-api33

permissions:
  contents: write

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/npm-license-checker-pr/
        with:
          DOLBYIO_GH_BOT_GPG_PRIVATE_KEY: ${{ secrets.DOLBYIO_GH_BOT_GPG_PRIVATE_KEY }}
          DOLBYIO_GH_BOT_USER_SIGNING_KEY_ID: ${{ secrets.DOLBYIO_GH_BOT_USER_SIGNING_KEY_ID }}
          USER_NAME: ${{ secrets.DOLBYIO_BOT_USER_NAME }}
          USER_EMAIL: ${{ secrets.DOLBYIO_BOT_USER_EMAIL }}
          NODE_VERSION: "16"
          YARN_INSTALL: "TRUE"
